# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "gui/src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# namespace settings
LIBNAMESPACE:
  namespace: "plfoundation"
  src: "bower_components/foundation-sites/**/*"
  dest: "bower_components/plfoundation-sites"
  needles:
    - "foundation"
    - "Foundation"
    - "FOUNDATION"
  replacements:
    - "plfoundation"
    - "PLFoundation"
    - "PLFOUNDATION"
   

# Gulp will reference these paths when it copies files
PATHS:

  ## build destination paths
  #
  
  # Path to dist folder
  dist: "dist"  
  # Path to patternlibrary GUI folder
  #patternlibrary: "gui"  
  
  
  ## vendor files (js,css)
  #
    
  # JS prequisites / basic requirements
  vendor_js:
    - "bower_components/jquery/dist/jquery.min.js"
    #- "bower_components/foundation-sites/dist/js/foundation.min.js"
    - "bower_components/plfoundation-sites/dist/js/plfoundation.min.js"
    - "bower_components/corejs-typeahead/dist/typeahead.bundle.min.js"
    - "bower_components/clipboard/dist/clipboard.min.js"
    - "bower_components/highlightjs/highlight.pack.min.js"
    
  # CSS prequisites / basic requirements
  vendor_css_basic:
    #- "bower_components/foundation-sites/dist/js/foundation-flex.min.css"
    - "bower_components/plfoundation-sites/dist/js/plfoundation-flex.min.css"
    
  vendor_css:
    - "bower_components/highlightjs/styles/**/*"
    
    
  ## PL frontend assets
  #
  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "gui/src/assets/**/*"
    - "!gui/src/assets/{img,js,scss}/**/*"
    
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    #- "gui/src/assets/css/font-awesome.min.css"
    #- "bower_components/foundation-sites/scss"
    - "bower_components/plfoundation-sites/scss"
    - "bower_components/motion-ui/src"

  # Paths to JavaScript libraries, which are compined into one file
  javascript:
  
    #- "gui/src/assets/vendor/modernizr.js"
    
    # Libraries requried by Foundation
    #- "bower_components/jquery/dist/jquery.js"
    #- "bower_components/what-input/dist/what-input.js"
    
    # Core Foundation files
    #- "bower_components/foundation-sites/js/foundation.core.js"
    #- "bower_components/foundation-sites/js/foundation.util.*.js"
    
    # Individual Foundation components
    # If you aren't using a component, just remove it from the list
    #- "bower_components/foundation-sites/js/foundation.abide.js"
    #- "bower_components/foundation-sites/js/foundation.accordion.js"
    #- "bower_components/foundation-sites/js/foundation.accordionMenu.js"
    #- "bower_components/foundation-sites/js/foundation.drilldown.js"
    #- "bower_components/foundation-sites/js/foundation.dropdown.js"
    #- "bower_components/foundation-sites/js/foundation.dropdownMenu.js"
    #- "bower_components/foundation-sites/js/foundation.equalizer.js"
    #- "bower_components/foundation-sites/js/foundation.interchange.js"
    #- "bower_components/foundation-sites/js/foundation.magellan.js"
    #- "bower_components/foundation-sites/js/foundation.offcanvas.js"
    #- "bower_components/foundation-sites/js/foundation.orbit.js"
    #- "bower_components/foundation-sites/js/foundation.responsiveMenu.js"
    #- "bower_components/foundation-sites/js/foundation.responsiveToggle.js"
    #- "bower_components/foundation-sites/js/foundation.reveal.js"
    #- "bower_components/foundation-sites/js/foundation.slider.js"
    #- "bower_components/foundation-sites/js/foundation.sticky.js"
    #- "bower_components/foundation-sites/js/foundation.tabs.js"
    #- "bower_components/foundation-sites/js/foundation.toggler.js"
    #- "bower_components/foundation-sites/js/foundation.tooltip.js"
    
    # Paths to your own project code are here
    
    ## GUI
    #- "bower_components/corejs-typeahead/dist/typeahead.bundle.min.js"
    #- "bower_components/clipboard/dist/clipboard.min.js"
    #- "bower_components/highlightjs/highlight.pack.min.js"
    
    ## emulator
    #- "bower_components/jScrollPane/script/jquery.jscrollpane.min.js"
    
    ## app core
    - 'gui/src/assets/js/patternlibrary.core.js'
    - 'gui/src/assets/js/patternlibrary.config.js'
    - 'gui/src/assets/js/libs/**/*.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.module.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.layoutbody.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.layouttoolbarsection.*.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.layouttoolbar.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.layoutelement.js'
    - 'gui/src/assets/js/components/layoutbuilder/layoutbuilder.*.js'
    - 'gui/src/assets/js/components/**/*.js'
    - 'gui/src/assets/js/modules/**/*.js'
    - 'gui/src/assets/js/patternlibrary.init.js'

    ## (optional) app init
    #- "gui/src/assets/js/!(app).js"
    - "gui/src/assets/js/app.js"
    
  ## test scripts
  #
  
  # vendors' amd Foundation's tests
  testFoundationJSfiles:
    - "test/javascript/plfoundation-sites/**/*.js"
    - "test/javascript/util/**/*.js"
    
  # PL frontend tests
  testPatternLibraryJSfiles:
    - "test/javascript/pattern_library/**/*.js"
